# set terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

# Set the prefix to C-Space.
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Make first window be 1
set -g base-index 1

# set vi mode
set-window-option -g mode-keys vi

# refresh 'status-left' and 'status-right' more often
set -g status-interval 5

# Fix escape key delay
set -sg escape-time 0

# Increase history limit
set -g history-limit 50000

# Increase time to display messages
set -g display-time 4000

# enable focus events
set -g focus-events on

# Enable mouse scroll
set -g mouse on

# Vi copy-mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# reload config file
bind r source-file ~/.tmux.conf

# set extended keys for pi agent compatibility
set -g extended-keys on
set -g extended-keys-format csi-u

# make links clickable
set -g allow-passthrough on

# colors
set -g @theme_bg "#1A1B26"
set -g @theme_fg "#a9b1d6"

set -g @theme_bblack "#2A2F41"
set -g @theme_blue "#7aa2f7"
set -g @theme_bgreen "#41a6b5"
set -g @theme_green "#73daca"
set -g @theme_yellow "#e0af68"

set -g mode-style "fg=#{@theme_bgreen},bg=#{@theme_bblack}"
set -g message-style "bg=#{@theme_blue},fg=#{@theme_bblack}"
set -g message-command-style "bg=#{@theme_blue},fg=#{@theme_bblack}"

# pane border
set -g pane-border-style "fg=#{@theme_bblack}"
set -g pane-active-border-style "fg=#{@theme_blue}"

# Status line
set -g status-style "fg=#{@theme_fg},bg=#{@theme_bg}"
set -g status-left-length 80
set -g status-left "#[fg=#{@theme_bblack},bg=#{@theme_blue},bold] #{?client_prefix,󰠠 ,#[dim]󰤂 }#[bold,nodim]#S "
set -g window-status-current-format "#[fg=#{@theme_green},bg=#{@theme_bblack}] #{?#{==:#{pane_current_command},ssh},󰣀 ,  }#[fg=#{@theme_fg},bold,nodim]#I:#W "
set -g window-status-format "#[fg=#{@theme_fg}] #{?#{==:#{pane_current_command},ssh},󰣀 ,  }#I:#W#[nobold,dim]#[fg=#{@theme_yellow}]#{?window_last_flag, 󰁯  , }"
set -g window-status-separator ""

set -g status-right "%Y-%m-%d %H:%M "

