# set terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

# Set the prefix to C-Space.
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Make first window be 1
set -g base-index 1

# set vi mode
set-window-option -g mode-keys vi

# refresh 'status-left' and 'status-right' more often
set -g status-interval 5

# Status line
set -g status-left-length 32
set -g status-left "[#S]"
set -g status-right "%Y-%m-%d %H:%M "

# Fix escape key delay
set -sg escape-time 0

# Increase history limit
set -g history-limit 50000

# Increase time to display messages
set -g display-time 4000

# Enable mouse scroll
set -g mouse on

# Vi copy-mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set extended keys for pi agent compatibility
set -g extended-keys on
set -g extended-keys-format csi-u

# make links clickable
set -g allow-passthrough on
